server:
  port: 8072

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres?currentSchema=aviatracker_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    liquibase:
      change-log: classpath:db.changelog/db.changelog-master.yaml
  kafka:
    streams:
      bootstrap-servers: ${KAFKA_HOST}:9092
      application-id: "kafka-streams-id"
      input-topic: "messages"
      output-topic: "accidents"
      group-id: "groupId"
